name: Build Container Image

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/ci_image.yaml
      - staas-cli.py
      - Dockerfile

jobs:
  build-ubuntu:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install ORAS
        run: |
          # ORAS is not an apk package, and to avoid creating many layers in the image, we download it here and copy it (Dockerfile)
          VERSION="1.2.2"
          curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
          mkdir -p oras-install/
          tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
          mv oras-install/oras ./oras
          rm -rf oras_${VERSION}_*.tar.gz oras-install/
          ls

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3.3.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: STh
        run: |
          ls -la
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/excid-io/staas-cli:latest

